name: 'react_widgets_demo'
version: 0.0.1
description: Demos for the react_widgets package.
#author: <your name> <email@example.com>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  react: any
  react_widgets:
    path: ../react_widgets
  intl: "^0.12.4"
